[package]
name = "smps"
version = "0.1.0"
edition = "2024"

[dependencies]
bitfield = "0.19.0"
blip_buf = "0.1.5"
num = "0.4.3"
paste = "1.0.15"

[build-dependencies]
cc = "1.2.16"

[dev-dependencies]
hound = "3.5.1"
