[package]
name = "smps"
version = "0.1.0"
edition = "2024"

[build-dependencies]
cc = "1.2.16"

[dev-dependencies]
hound = "3.5.1"

[dependencies]
bitflags = "2.9.1"
mdcomp = { version = "0.1.0", path = "../mdcomp" }
