// #define CHECK_STUFF(loc) 1
#include "opcodes.h"
#include "system.h"

static bool game_initialized = false;

typedef enum {
  GAMESTATE_SEGA_INIT,
  GAMESTATE_SEGA_PALCYCLE,
  GAMESTATE_SEGA_SETENDWAITTIME,
  GAMESTATE_SEGA_WAITEND,

  GAMESTATE_TITLE_INIT,
  GAMESTATE_TITLE_LOOP,
  GAMESTATE_LEVELSELECT_LOOP,

  GAMESTATE_DEMO_INIT,
  GAMESTATE_DEMO_LOOP,

  GAMESTATE_LEVEL_INIT,
  GAMESTATE_LEVEL_TITLECARD,
  GAMESTATE_LEVEL_INTRODELAY,
  GAMESTATE_LEVEL_MAINLOOP,
  GAMESTATE_LEVEL_DEMOFADE,

  GAMESTATE_SPECIAL_INIT,
  GAMESTATE_SPECIAL_MAINLOOP,
  GAMESTATE_SPECIAL_FINISHLOOP,
  GAMESTATE_SPECIAL_EXIT,

  GAMESTATE_CONTINUE_INIT,
  GAMESTATE_CONTINUE_LOOP,

  GAMESTATE_ENDING_INIT,
  GAMESTATE_ENDING_FADEIN,
  GAMESTATE_ENDING_MAINLOOP,
  GAMESTATE_ENDING_ALLEMERALDS,

  GAMESTATE_CREDITS_INIT,
  GAMESTATE_CREDITS_MAINLOOP,

  GAMESTATE_TRYAGAIN_INIT,
  GAMESTATE_TRYAGAIN_MAINLOOP,
} GAMESTATE;

GAMESTATE game_state;

void init_game(void) {}

void run_game_frame(bool reset) {
  if (reset) {
    game_initialized = false;
  }
  if (!game_initialized) {
    init_game();
  }
}